language: c
php:
- 5.6

sudo: required
services:
- docker

before_script:
- sudo apt-get update && sudo apt-get install php5-cli
- if [ -n "$GITHUB_TOKEN" ]; then composer config -g github-oauth.github.com $GITHUB_TOKEN; fi
- composer install

script:
- php vendor/bin/robo check:robo-file-version
- php .travis/phppec.php component/ libraries/ modules/ plugins/
- php .travis/phpcs.php
- php .travis/misseddebugcodechecker.php component/ libraries/ modules/ plugins/
- vendor/bin/robo run:docker
